export const DEFAULT_CATEGORIES = [
  { id: 'vestuario', name: 'Vestuário', icon: 'bx bx-closet', color: '#EC4899', description: 'Roupas e acessórios' },
  { id: 'moradia', name: 'Moradia', icon: 'bx bx-home', color: '#3B82F6', description: 'Custos de casa' },
  { id: 'impostos', name: 'Impostos', icon: 'bx bx-money', color: '#EF4444', description: 'Taxas e tributos' },
  { id: 'salario', name: 'Salário', icon: 'bx bx-dollar-circle', color: '#10B981', description: 'Renda principal' },
  { id: 'seguro', name: 'Seguro', icon: 'bx bx-shield', color: '#6366F1', description: 'Seguros diversos' },
  { id: 'aluguel', name: 'Aluguel', icon: 'bx bx-building-house', color: '#8B5CF6', description: 'Aluguel mensal' },
  { id: 'assinaturas', name: 'Assinaturas', icon: 'bx bx-calendar-star', color: '#F59E0B', description: 'Serviços recorrentes' },
  { id: 'supermercado', name: 'Mercado', icon: 'bx bx-cart', color: '#F97316', description: 'Compras do mês' },
  { id: 'agua', name: 'Água', icon: 'bx bx-water', color: '#06B6D4', description: 'Conta de água' },
  { id: 'gas', name: 'Gás', icon: 'bx bx-cloud', color: '#64748B', description: 'Gás de cozinha' },
  { id: 'internet', name: 'Internet', icon: 'bx bx-wifi', color: '#3B82F6', description: 'Internet e TV' },
  { id: 'energia', name: 'Energia elétrica', icon: 'bx bx-plug', color: '#EAB308', description: 'Conta de luz' },
  { id: 'restaurantes', name: 'Restaurantes', icon: 'bx bx-restaurant', color: '#F43F5E', description: 'Comer fora' },
  { id: 'combustivel', name: 'Combustível', icon: 'bx bx-gas-pump', color: '#71717A', description: 'Abastecimento' },
  { id: 'emprestimos', name: 'Empréstimos', icon: 'bx bx-money-withdraw', color: '#7C3AED', description: 'Pagamento de dívidas' },
  { id: 'financiamentos', name: 'Financiamentos', icon: 'bx bx-credit-card', color: '#059669', description: 'Parcelas de bens' },
  // New categories
  { id: 'alimentacao_compras', name: 'Alimentação Compras', icon: 'bx bx-shopping-bag', color: '#FFC107', description: 'Compras de alimentos em geral' },
  { id: 'cuidados_pessoais', name: 'Cuidados Pessoais', icon: 'bx bx-face', color: '#FF7043', description: 'Produtos de higiene e beleza' },
  { id: 'educacao', name: 'Educação', icon: 'bx bx-book-open', color: '#9C27B0', description: 'Cursos, livros e mensalidades' },
  { id: 'familia_filhos', name: 'Família e Filhos', icon: 'bx bx-child', color: '#00BCD4', description: 'Despesas com a família e crianças' },
  { id: 'investimentos', name: 'Investimentos', icon: 'bx bx-trending-up', color: '#4CAF50', description: 'Aplicações financeiras' },
  { id: 'lazer_hobbies', name: 'Lazer e Hobbies', icon: 'bx bx-game', color: '#E91E63', description: 'Entretenimento e passatempos' },
  { id: 'animais_estimacao', name: 'Animais de Estimação', icon: 'bx bx-paw', color: '#8D6E63', description: 'Despesas com pets' },
  { id: 'presentes_doacoes', name: 'Presentes e Doações', icon: 'bx bx-gift', color: '#607D8B', description: 'Presentes e contribuições' },
  { id: 'saude', name: 'Saúde', icon: 'bx bx-plus-medical', color: '#F44336', description: 'Consultas, remédios e planos de saúde' },
  { id: 'trabalho', name: 'Trabalho', icon: 'bx bx-briefcase', color: '#795548', description: 'Despesas relacionadas ao trabalho' },
  { id: 'transporte', name: 'Transporte', icon: 'bx bx-bus', color: '#3F51B5', description: 'Passagens, taxi, apps de transporte' },
  { id: 'viagem', name: 'Viagem', icon: 'bx bx-plane-alt', color: '#03A9F4', description: 'Passagens, hospedagem e passeios' },
  { id: 'jogos', name: 'Jogos', icon: 'bx bx-joystick', color: '#673AB7', description: 'Jogos eletrônicos e de tabuleiro' },
];