// Display name/description come from the `default_categories.<id>` i18n key (see locales/*.json),
// so this file only holds the non-localized preset data.
export const DEFAULT_CATEGORIES = [
  { id: 'vestuario', icon: 'bx bx-closet', color: '#EC4899' },
  { id: 'moradia', icon: 'bx bx-home', color: '#3B82F6' },
  { id: 'impostos', icon: 'bx bx-money', color: '#EF4444' },
  { id: 'salario', icon: 'bx bx-dollar-circle', color: '#10B981', budgetEnabled: false },
  { id: 'seguro', icon: 'bx bx-shield', color: '#6366F1' },
  { id: 'aluguel', icon: 'bx bx-building-house', color: '#8B5CF6' },
  { id: 'assinaturas', icon: 'bx bx-calendar-star', color: '#F59E0B' },
  { id: 'supermercado', icon: 'bx bx-cart', color: '#F97316' },
  { id: 'agua', icon: 'bx bx-water', color: '#06B6D4' },
  { id: 'gas', icon: 'bx bx-cloud', color: '#64748B' },
  { id: 'internet', icon: 'bx bx-wifi', color: '#3B82F6' },
  { id: 'energia', icon: 'bx bx-plug', color: '#EAB308' },
  { id: 'restaurantes', icon: 'bx bx-restaurant', color: '#F43F5E' },
  { id: 'combustivel', icon: 'bx bx-gas-pump', color: '#71717A' },
  { id: 'emprestimos', icon: 'bx bx-money-withdraw', color: '#7C3AED' },
  { id: 'financiamentos', icon: 'bx bx-credit-card', color: '#059669' },
  // New categories
  { id: 'alimentacao', icon: 'bx bx-basket', color: '#FFC107' },
  { id: 'cuidados_pessoais', icon: 'bx bx-face', color: '#FF7043' },
  { id: 'educacao', icon: 'bx bx-book-open', color: '#9C27B0' },
  { id: 'familia_filhos', icon: 'bx bx-child', color: '#00BCD4' },
  { id: 'investments', icon: 'bx bx-trending-up', color: '#4CAF50', budgetEnabled: false },
  { id: 'lazer_hobbies', icon: 'bx bx-game', color: '#E91E63' },
  { id: 'animais_estimacao', icon: 'bx bx-paw', color: '#8D6E63' },
  { id: 'presentes_doacoes', icon: 'bx bx-gift', color: '#607D8B' },
  { id: 'saude', icon: 'bx bx-plus-medical', color: '#F44336' },
  { id: 'trabalho', icon: 'bx bx-briefcase', color: '#795548' },
  { id: 'transporte', icon: 'bx bx-bus', color: '#3F51B5' },
  { id: 'viagem', icon: 'bx bx-plane-alt', color: '#03A9F4' },
  { id: 'compras', icon: 'bx bx-shopping-bag', color: '#D946EF' },
  { id: 'fatura_cartao', icon: 'bx bx-receipt', color: '#0891B2' },
  { id: 'plano_celular', icon: 'bx bx-mobile', color: '#2563EB' },
  { id: 'heranca', icon: 'bx bx-scroll', color: '#A16207' },
];