// Portuguese search synonyms for each icon slug, so users can find icons
// without knowing the (English) boxicons name. Keyed by the same 'bx-*' slug
// used in IconSelector.jsx / BxIcon.jsx.
export const ICON_SEARCH_KEYWORDS_PT = {
  'bx-target-lock': ['meta', 'alvo', 'objetivo'],
  'bx-money': ['dinheiro', 'grana'],
  'bx-trophy': ['troféu', 'conquista', 'prêmio'],
  'bx-home': ['casa', 'lar', 'residência'],
  'bx-car': ['carro', 'veículo', 'automóvel'],
  'bx-plane': ['avião', 'voo', 'viagem'],
  'bx-plane-alt': ['avião', 'voo', 'viagem'],
  'bx-book': ['livro', 'leitura'],
  'bx-book-open': ['livro', 'leitura', 'estudo'],
  'bx-graduation': ['educação', 'formatura', 'escola'],
  'bx-briefcase': ['trabalho', 'maleta', 'pasta', 'emprego'],
  'bx-gift': ['presente', 'mimo'],
  'bx-heart': ['coração', 'amor', 'saúde'],
  'bx-star': ['estrela', 'favorito'],
  'bx-diamond': ['diamante', 'joia'],
  'bx-mobile': ['celular', 'telefone', 'smartphone'],
  'bx-laptop': ['notebook', 'computador', 'laptop'],
  'bx-camera': ['câmera', 'foto', 'fotografia'],
  'bx-music': ['música', 'som'],
  'bx-video': ['vídeo', 'filme'],
  'bx-joystick': ['jogo', 'videogame', 'controle'],
  'bx-dumbbell': ['academia', 'halter', 'musculação', 'exercício'],
  'bx-plus-medical': ['saúde', 'medicamento', 'remédio'],
  'bx-building': ['prédio', 'edifício', 'empresa'],
  'bx-building-house': ['casa', 'imóvel', 'propriedade'],
  'bx-store': ['loja', 'comércio'],
  'bx-cart': ['carrinho', 'compras', 'mercado'],
  'bx-shopping-bag': ['sacola', 'compras', 'shopping'],
  'bx-wallet': ['carteira', 'dinheiro'],
  'bx-credit-card': ['cartão', 'crédito'],
  'bx-dollar': ['dólar', 'moeda'],
  'bx-euro': ['euro', 'moeda'],
  'bx-bitcoin': ['bitcoin', 'cripto', 'criptomoeda'],
  'bx-pie-chart': ['gráfico', 'pizza', 'relatório'],
  'bx-bar-chart': ['gráfico', 'barras', 'relatório'],
  'bx-trending-up': ['crescimento', 'alta', 'lucro', 'investimento'],
  'bx-cloud': ['nuvem', 'tempo'],
  'bx-sun': ['sol', 'verão'],
  'bx-moon': ['lua', 'noite'],
  'bx-water': ['água'],
  'bx-bulb': ['luz', 'energia', 'lâmpada', 'ideia'],
  'bx-restaurant': ['restaurante', 'comida', 'jantar', 'refeição'],
  'bx-coffee': ['café', 'bebida'],
  'bx-bed': ['cama', 'dormir', 'quarto'],
  'bx-shield': ['segurança', 'proteção', 'seguro'],
  'bx-wifi': ['internet', 'conexão'],
  'bx-plug': ['energia', 'elétrica', 'tomada'],
  'bx-gas-pump': ['combustível', 'gasolina', 'posto'],
  'bx-closet': ['armário', 'guarda-roupa'],
  'bx-face': ['rosto', 'beleza', 'estética'],
  'bx-child': ['criança', 'filho', 'filha'],
  'bx-paw': ['pet', 'animal', 'cachorro', 'gato'],
  'bx-bus': ['ônibus', 'transporte'],
  'bx-group': ['grupo', 'pessoas', 'equipe', 'família'],
  'bx-bank': ['banco', 'financeiro'],
  'bx-landmark': ['banco', 'prédio', 'patrimônio'],
  'bx-piggy-bank': ['poupança', 'economia', 'cofrinho'],
  'bx-safe': ['cofre', 'segurança'],
  'bx-calculator': ['calculadora', 'cálculo'],
  'bx-coins': ['moedas', 'dinheiro'],
  'bx-chart-line': ['gráfico', 'investimento', 'linha'],
  'bx-umbrella': ['guarda-chuva', 'seguro', 'proteção'],
  'bx-pill': ['remédio', 'medicamento', 'farmácia'],
  'bx-syringe': ['vacina', 'injeção', 'saúde'],
  'bx-taxi': ['táxi', 'corrida', 'transporte'],
  'bx-train': ['trem', 'transporte'],
  'bx-subway': ['metrô', 'transporte'],
  'bx-truck': ['caminhão', 'mudança', 'entrega'],
  'bx-motorcycle': ['moto', 'motocicleta'],
  'bx-ship': ['navio', 'barco', 'cruzeiro'],
  'bx-spa': ['spa', 'relaxamento', 'bem-estar'],
  'bx-popcorn': ['pipoca', 'cinema'],
  'bx-ticket': ['ingresso', 'bilhete', 'passagem'],
  'bx-beer': ['cerveja', 'bebida', 'bar'],
  'bx-wine': ['vinho', 'bebida'],
  'bx-pizza': ['pizza', 'comida'],
  'bx-tv': ['televisão'],
  'bx-dog': ['cachorro', 'cão', 'pet'],
  'bx-cat': ['gato', 'pet'],
  'bx-tree': ['árvore', 'natureza', 'jardim'],
  'bx-pound': ['libra', 'moeda'],
  'bx-yen': ['iene', 'moeda'],
  'bx-ruble': ['rublo', 'moeda'],
  'bx-rupee': ['rupia', 'moeda'],
  'bx-won': ['moeda'],
  'bx-lira': ['lira', 'moeda'],
  'bx-currency-note': ['nota', 'dinheiro', 'cédula'],
  'bx-crypto': ['cripto', 'criptomoeda', 'moeda digital'],
  'bx-wallet-alt': ['carteira', 'cripto'],
  'bx-coin': ['moeda'],
  'bx-headphone': ['fone', 'fones de ouvido', 'áudio'],
  'bx-speaker': ['caixa de som', 'alto-falante', 'som'],
  'bx-printer': ['impressora'],
  'bx-keyboard': ['teclado'],
  'bx-mouse': ['mouse'],
  'bx-usb': ['pendrive'],
  'bx-server': ['servidor'],
  'bx-radio': ['rádio'],
  'bx-hard-drive': ['hd', 'disco rígido', 'armazenamento'],
  'bx-chip': ['chip', 'processador'],
  'bx-devices': ['dispositivos', 'eletrônicos'],
  'bx-watch': ['relógio'],
  'bx-microphone': ['microfone'],
  'bx-battery': ['bateria', 'pilha'],
  'bx-cctv': ['câmera de segurança', 'vigilância'],
  'bx-chair': ['cadeira'],
  'bx-couch': ['sofá'],
  'bx-table': ['mesa'],
  'bx-cabinet': ['armário', 'gabinete'],
  'bx-fridge': ['geladeira', 'refrigerador'],
  'bx-washer': ['máquina de lavar', 'lavadora'],
  'bx-dishwasher': ['lava-louças'],
  'bx-microwave': ['micro-ondas'],
  'bx-oven': ['forno'],
  'bx-air-conditioner': ['ar-condicionado'],
  'bx-fan': ['ventilador'],
  'bx-door': ['porta'],
  'bx-window': ['janela'],
  'bx-garage': ['garagem'],
  'bx-shower': ['chuveiro', 'ducha'],
  'bx-scroll': ['herança', 'testamento', 'documento'],
  'bx-gavel': ['jurídico', 'advogado', 'lei', 'tribunal'],
  'bx-key': ['chave', 'herança', 'imóvel'],
  'bx-signature': ['assinatura', 'contrato'],
  'bx-stamp': ['carimbo', 'cartório', 'autenticação'],
  'bx-buildings': ['imóveis', 'propriedades', 'patrimônio'],
  'bx-medal-star': ['medalha', 'conquista', 'legado'],
  'bx-handshake': ['acordo', 'negócio', 'parceria'],
  'bx-jewelry': ['joia', 'joias', 'herança'],
  'bx-luggage': ['mala', 'bagagem', 'viagem'],
  'bx-compass': ['bússola', 'direção'],
  'bx-globe': ['mundo', 'globo', 'viagem', 'internacional'],
  'bx-backpack': ['mochila'],
  'bx-basketball': ['basquete'],
  'bx-football': ['futebol americano'],
  'bx-golf': ['golfe'],
  'bx-guitar': ['violão', 'guitarra'],
  'bx-palette': ['arte', 'pintura', 'paleta'],
  'bx-table-tennis': ['ping-pong', 'tênis de mesa'],
  'bx-rugby': ['rugby'],
  'bx-skateboard': ['skate'],
  'bx-tooth': ['dente', 'dentista'],
  'bx-thermometer': ['termômetro', 'febre'],
  'bx-dna': ['genética'],
  'bx-ambulance': ['ambulância', 'emergência'],
  'bx-recycle': ['reciclagem', 'reciclar'],
  'bx-broom': ['vassoura', 'limpeza'],
  'bx-fire': ['fogo', 'incêndio'],
  'bx-rocket': ['foguete', 'lançamento'],
  'bx-robot': ['robô', 'tecnologia'],
  'bx-school': ['escola', 'educação'],
  'bx-graduation-cap': ['formatura', 'faculdade', 'educação'],
  'bx-anchor': ['âncora', 'navio'],
  'bx-snowflake': ['neve', 'inverno', 'frio'],
  'bx-pool': ['piscina'],
  'bx-route': ['rota', 'caminho', 'trajeto'],
  'bx-cake': ['bolo', 'aniversário', 'festa'],
  'bx-balloon': ['balão', 'festa'],
  'bx-basket': ['cesta', 'cesto', 'compras'],
  'bx-leaf': ['folha', 'natureza', 'planta'],
};